EBookLibrary/Controllers/LibraryManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EBookLibraryData;
using EBookLibraryData.Models;
using EBookLibraryData.Models.ViewModels.LibraryManage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EBookLibrary.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LibraryManageController : Controller
    {
        private readonly IBooksManage _manage;
        private readonly IQueue _queue;
        private readonly ILoanHistory _loanHistory;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IAuthors _author;
        private readonly IPublishers _publisher;
        private readonly ICategory _category;
        private readonly ILoans _loans;
        private readonly IUserManage _users;
        private const int NumberToTake = 1000;

        public LibraryManageController(IBooksManage manage,
            IQueue queue,
            ILoanHistory loanHistory,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IAuthors author,
            IPublishers publisher,
            ICategory category,
            ILoans loans,
            IUserManage users)
        {
            _manage = manage;
            _queue = queue;
            _userManager = userManager;
            _signInManager = signInManager;
            _loanHistory = loanHistory;
            _author = author;
            _publisher = publisher;
            _category = category;
            _loans = loans;
            _users = users;
        }

        private readonly List<string[]> operations = new List<string[]>()
        {
            new string[]{ "Dodaj nową książkę", "add" },
            new string[]{ "Modyfikuj dane książki", "update" },
            new string[]{ "Usuń książkę", "delete" },
            new string[]{ "Wyszukaj książki", "select" }
        };

        private readonly List<string[]> menuOptions = new List<string[]>() {
            new string[]{
                "Books",
                "Książki",
            },
            new string[]{
                "Authors",
                "Autorzy"
            },
            new string[]{
                "Publishers",
                "Wydawcy"
            },
            new string[]{
                "Users",
                "Użytkownicy"
            },
            new string[]{
                "Loans",
                "Wypożyczenia",
            },
            new string[]{
                "Queues",
                "Kolejki"
            },
            new string[]{
                "Categories",
                "Kategorie"
            },
            new string[]{
                "LoanHistories",
                "Historie wypożyczeń"
            }
        };
        enum Option
        {
            Name,
            CommonName,
            Books = 0,
            Authors,
            Publishers,
            Users,
            Loans,
            Queues,
            Categories,
            LoanHistories
        };

        enum OperationError
        {
            add = 0,
            remove = 1,
            modify = 2
        };

        [HttpGet]
        public IActionResult Books()
        {
            ViewData["Title"] = "Książki";
            ViewData["Options"] = menuOptions;
            ViewData["Selected"] = menuOptions[(int)Option.Books][(int)Option.Name];
            return View(new BooksManageViewModel {
                Categories = _manage.GetAllCategories(),
                Authors = _manage.GetAllAuthors(),
                Publishers = _publisher.GetMany(NumberToTake),
                Books = _manage.GetMany(NumberToTake),
                
            });
        }

        [HttpPost]
        public IActionResult Books(BooksManageViewModel model)
        {
            ViewData["Title"] = "Książki";
            ViewData["Options"] = menuOptions;
            ViewData["Selected"] = menuOptions[(int)Option.Books][(int)Option.Name];
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddBook(BooksManageViewModel model)
        {
            ViewData["Title"] = "Książki";
            ViewData["Options"] = menuOptions;
            ViewData["Selected"] = menuOptions[(int)Option.Books][(int)Option.Name];
            model.RemovedSuccessfully = false;
            model.AddedSuccessfully = false;
            model.AddError = false;
            model.RemoveError = false;
            model.ModifiedSuccessfully = false;
            model.ModifiedError = false;

            if (await _manage.Add(model.Title, model.ISBN, model.Pages, model.Author, model.Publisher,
                model.Category, model.Book, model.BookCovering, model.CopiesCount))
            {
                model.AddedSuccessfully = true;
            }
            else model.AddError = true;

            model.Take = NumberToTake;
            model.Authors = _author.GetMany(model.Take);
            model.Categories = _manage.GetAllCategories();
            model.Publishers = _publisher.GetMany(NumberToTake);
            model.Books = _manage.GetMany(NumberToTake);
            return View("Books", model);
        }

        [HttpPost]
        public IActionResult RemoveBook(BooksManageViewModel model)
        {
            ViewData["Title"] = "Książki";
            ViewData["Options"] = menuOptions;
            ViewData["Selected"] = menuOptions[(int)Option.Books][(int)Option.Name];
            model.RemovedSuccessfully = false;
            model.AddedSuccessfully = false;
            model.AddError = false;
            model.RemoveError = false;
            model.ModifiedSuccessfully = false;
            model.ModifiedError = false;

            if (_manage.DeleteById((int)model.Id))
            {
                model.RemovedSuccessfully = true;
            }
            else model.RemoveError = true;

            model.Take = NumberToTake;
            model.Authors = _author.GetMany(model.Take);
            model.Categories = _manage.GetAllCategories();
            model.Publishers = _publisher.GetMany(NumberToTake);
            model.Books = _manage.GetMany(NumberToTake);
            return RedirectToAction("Books", model);
        }

        [HttpPost]
        public IActionResult ModifyBook(BooksManageViewModel model)
        {
            ViewData["Title"] = "Książki";
            ViewData["Options"] = menuOptions;
            ViewData["Selected"] = menuOptions[(int)Option.Books][(int)Option.Name];
            model.RemovedSuccessfully = false;
            model.AddedSuccessfully = false;
            model.AddError = false;
            model.RemoveError = false;
            model.ModifiedSuccessfully = false;
            model.ModifiedError = false;

            if (_manage.Modify(model))
            {
                model.ModifiedSuccessfully = true;
                model.Title = null;
                model.CopiesCount = null;
                model.BookCovering = null;
                model.Pages = null;
                model.Author = null;
                model.Publisher = null;
                model.ISBN = null;
            }
            else model.ModifiedError = true;

            model.Take = NumberToTake;
            model.Authors = _author.GetMany(model.Take);
            model.Categories = _manage.GetAllCategories();
            model.Publishers = _publisher.GetMany(NumberToTake);
            model.Books = _manage.GetMany(NumberToTake);
            return RedirectToAction("Books", model);
        }

        [HttpGet]
        public IActionResult Authors()
        {
            ViewData["Title"] = "Autorzy";
            ViewData["Options"] = menuOptions;
            ViewData["Selected"] = menuOptions[(int)Option.Authors][(int)Option.Name];
            return View(new AuthorsManageViewModel
            {
                Authors = _author.GetMany(NumberToTake),
                Take = NumberToTake
            });
        }

        [HttpPost]
        public IActionResult Authors(AuthorsManageViewModel model)
        {
            ViewData["Title"] = "Autorzy";
            ViewData["Options"] = menuOptions;
            ViewData["Selected"] = menuOptions[(int)Option.Authors][(int)Option.Name];
            model.RemovedSuccessfully = false;
            model.AddedSuccessfully = false;
            model.AddError = false;
            model.RemoveError = false;
            if (model.Name != null)
            {
                if(_author.Add(model.Name))
                {
                    model.AddedSuccessfully = true;
                }
                else model.AddError = true;
            }
            else if(model.AuthorId != null)
            {
                if (_author.Remove((int)model.AuthorId))
                {
                    model.RemovedSuccessfully = true;
                }
                else model.RemoveError = true;
            }
            model.Take = NumberToTake;
            model.Authors = _author.GetMany(model.Take);
            model.AuthorId = null;
            model.Name = null;
            return View(model);
        }

        [HttpGet]
        public IActionResult Publishers()
        {
            ViewData["Title"] = "Wydawcy";
            ViewData["Options"] = menuOptions;
            ViewData["Selected"] = menuOptions[(int)Option.Publishers][(int)Option.Name];
            return View(new PublisherManageViewModel
            {
                Publishers = _publisher.GetMany(NumberToTake),
                Take = NumberToTake
            });
        }

        [HttpPost]
        public IActionResult Publishers(PublisherManageViewModel model)
        {
            ViewData["Title"] = "Wydawcy";
            ViewData["Options"] = menuOptions;

EBookLibrary/Views/LibraryManage/Authors.cshtml
@model EBookLibraryData.Models.ViewModels.LibraryManage.AuthorsManageViewModel

@{
    Layout = "_ManageLibraryLayout";
}

<h3 class="pb-2">
    @ViewData["Title"]
    <span style="display: inline-block; float: right">
        <span style="display: inline-block">
            <!-- Button trigger modal -->
            <button class="btn btn-success" data-toggle="modal" data-target="#add-modal"><span class="fa fa-plus"></span></button>
        </span>
    </span>
</h3>
@if (Model.AddedSuccessfully)
{
    <div class="alert alert-success" role="alert">
        @Model.AddSuccess
    </div>
}
else if (Model.AddError)
{
    <div class="alert alert-danger" role="alert">
        @Model.AddFailed
    </div>
}
@if (Model.RemovedSuccessfully)
{
    <div class="alert alert-success" role="alert">
        @Model.RemoveSuccess
    </div>
}
else if (Model.RemoveError)
{
    <div class="alert alert-danger" role="alert">
        @Model.RemoveFailed
    </div>
}

<!-- Modal -->
<div class="modal fade" id="add-modal" tabindex="-1" role="dialog" aria-labelledby="add-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="add-modal-label">Dodaj nowego autora</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="LibraryManage" asp-action="Authors" method="post" id="add-author-form">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                <button class="btn btn-success" form="add-author-form">Dodaj</button>
            </div>
        </div>
    </div>
</div>

@if (Model.Authors != null)
{
    <table id="table" class="table table-striped table-bordered" style="width: 100%">
        <thead>
            <tr>
                @foreach (var column in Model.ColumnNames)
                {
                    <th>@column</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var author in Model.Authors)
            {
                <tr>
                    <td>@author.AuthorId</td>
                    <td>@author.Name</td>
                    <td>
                        <div class="float-left pl-1 pb-3">
                            <!-- Button trigger modal -->
                            <button class="btn btn-danger" data-toggle="modal" data-target="#remove-modal-@author.AuthorId"><span class="fa fa-times"></span></button>

                            <!-- Modal -->
                            <div class="modal fade" id="remove-modal-@author.AuthorId" tabindex="-1" role="dialog" aria-labelledby="remove-modal-@author.AuthorId-label" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="remove-modal-@author.AuthorId-label">Usuwanie autora</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form asp-controller="LibraryManage" asp-action="Authors" method="post" id="remove-author-form-@author.AuthorId"></form>
                                            Czy na pewno chcesz usunąć tego autora?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                                            <button class="btn btn-danger" name="AuthorId" value="@author.AuthorId" form="remove-author-form-@author.AuthorId">Usuń</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info" role="alert">
        Brak elementów do wyświetlenia.
    </div>
}

EBookLibrary/Views/LibraryManage/Books.cshtml
@model EBookLibraryData.Models.ViewModels.LibraryManage.BooksManageViewModel

@{
    Layout = "_ManageLibraryLayout";
}

<script src="~/js/managePanel.js"></script>
<script src="~/js/pagination.js"></script>
<script src="~/js/doubleInput.js"></script>

<h3 class="pb-2">
    @ViewData["Title"]
    <span style="display: inline-block; float: right">
        <span style="display: inline-block">
            <!-- Button trigger modal -->
            <button class="btn btn-success" data-toggle="modal" data-target="#add-modal"><span class="fa fa-plus"></span></button>
        </span>
        <span style="display: inline-block">
            <button class="btn btn-primary" id="export-modal"><span class="fa fa-file-pdf"></span></button>
        </span>
    </span>
</h3>
@if (Model.AddedSuccessfully)
{
    <div class="alert alert-success" role="alert">
        @Model.AddSuccess
    </div>
}
else if (Model.AddError)
{
    <div class="alert alert-danger" role="alert">
        @Model.AddFailed
    </div>
}
@if (Model.RemovedSuccessfully)
{
    <div class="alert alert-success" role="alert">
        @Model.RemoveSuccess
    </div>
}
else if (Model.RemoveError)
{
    <div class="alert alert-danger" role="alert">
        @Model.RemoveFailed
    </div>
}

<!-- Modal -->
<div class="modal fade" id="add-modal" tabindex="-1" role="dialog" aria-labelledby="add-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="add-modal-label">Dodaj nową książkę</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row p-2">
                    <div class="col-xs-12">
                        <form enctype="multipart/form-data" asp-controller="LibraryManage" asp-action="AddBook" method="post" id="manage-books-form">
                            <div class="form-row">
                                <div class="col-xs-12 col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="Title"></label>
                                        <input asp-for="Title" class="form-control" id="title" />
                                        <span asp-validation-for="Title" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <label asp-for="BookCovering"></label>
                                        <br />
                                        <img class="img-fluid p-2" id="book-covering-image"
                                             src="~/images/Icons-master/picol_latest_prerelease_svg/document_image_add.svg" />
                                        <input asp-for="BookCovering" class="form-control-file" id="book-covering" accept="image/*" />
                                        <span asp-validation-for="BookCovering" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <label asp-for="Author"></label>
                                        <select asp-for="Author" class="form-control" id="author" multiple>
                                            <option value=""></option>
                                            @foreach (var author in Model.Authors)
                                            {
                                                <option value="@author.Name">@author.Name</option>
                                            }
                                        </select>
                                        <span asp-validation-for="Author" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <label asp-for="Book"></label>
                                        <input asp-for="Book" class="form-control-file" id="book" accept=".pdf" />
                                        <span asp-validation-for="Book" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <label asp-for="ISBN"></label>
                                        <input asp-for="ISBN" class="form-control" id="isbn" min="0" />
                                        <span asp-validation-for="ISBN" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <label asp-for="Pages"></label>
                                        <input asp-for="Pages" class="form-control" id="pages" min="0" />
                                        <span asp-validation-for="Pages" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <label asp-for="Publisher"></label>
                                        <select asp-for="Publisher" class="form-control" id="publisher">
                                            <option value=""></option>
                                            @if (Model.Publishers != null)
                                            {
                                                @foreach (var i in Model.Publishers)
                                                {
                                                    <option value="@i.Name">@i.Name</option>
                                                }
                                            }
                                        </select>
                                        <span asp-validation-for="Publisher" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <label asp-for="CopiesCount"></label>
                                        <input asp-for="CopiesCount" class="form-control" id="copies-count" min="0" />
                                        <span asp-validation-for="CopiesCount" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <label asp-for="Category"></label>
                                        <select asp-for="Category" class="form-control" id="category">
                                            <option value=""></option>
                                            @if (Model.Categories != null)
                                            {
                                                @foreach (var i in Model.Categories)
                                                {
                                                    <option value="@i.Name">@i.Name</option>
                                                }
                                            }
                                        </select>
                                        <span asp-validation-for="Category" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                <button class="btn btn-success" form="manage-books-form">Dodaj</button>
            </div>
        </div>
    </div>
</div>

@if (Model.Books != null)
{
    <table id="table" class="table table-striped table-bordered" style="width: 100%">
        <thead>
            <tr>
                @foreach (var column in Model.ColumnNames)
                {
                    <th>@column</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model.Books)
            {
                <tr>
                    <td><img class="book-covering-image-table" src="~/images/BookCovering/@book.CoveringPath" /></td>
                    <td>@book.BookId</td>
                    <td>
                        <form asp-controller="LibraryManage" asp-action="ModifyBook" method="post">
                            <div class="form-group">
                                <input type="hidden" asp-for="Id" value="@book.BookId" />
                                <input asp-for="Title" class="form-control" value="@book.Title" onchange="this.form.submit();" />
                            </div>
                        </form>
                    </td>
                    <td>@book.LoansCount</td>
                    <td>
                        <form asp-controller="LibraryManage" asp-action="ModifyBook" method="post">
                            <div class="form-group">
                                <input type="hidden" asp-for="Id" value="@book.BookId"/>
                                <input asp-for="CopiesCount" class="form-control" value="@book.CopiesCount" onchange="this.form.submit();" />
                            </div>
                        </form>
                    </td>
                    <td>
                        <div class="float-left pl-1 pb-3">
                            <form asp-controller="Home" asp-action="BookPreview" method="post">
                                <Button type="submit" class="btn btn-primary" name="BookId" value="@book.BookId"><span class="fa fa-info"></span></Button>
                            </form>
                        </div>
                        <div class="float-left pl-1 pb-3">
                            <!-- Button trigger modal -->
                            <button class="btn btn-danger" data-toggle="modal" data-target="#remove-modal-@book.BookId"><span class="fa fa-times"></span></button>

                            <!-- Modal -->
<div class="modal fade" id="remove-modal-@book.BookId" tabindex="-1" role="dialog" aria-labelledby="remove-modal-@book.BookId-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="remove-modal-@book.BookId-label">Usuwanie książki</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="LibraryManage" asp-action="RemoveBook" method="post" id="remove-book-form-@book.BookId"></form>
                Czy na pewno chcesz usunąć tę książkę?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                <button class="btn btn-danger" name="Id" value="@book.BookId" form="remove-book-form-@book.BookId">Usuń</button>
            </div>
        </div>
    </div>
</div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info" role="alert">
        Brak elementów do wyświetlenia
    </div>
}
<script>
    let btn = document.getElementById('export-modal');
    btn.addEventListener('click', () => {
        let doc = new jsPDF('p', 'pt');
        let elem = document.getElementById("table");
        let res = doc.autoTableHtmlToJson(elem);

        doc.addFont('Abha.ttf', 'Abha', 'normal', 'Identity-H');
        doc.setFont('Abha');
        doc.autoTable(res.columns, res.data, {
            styles: { fillColor: [100, 255, 255] },
            columnStyles: {
                id: { fillColor: 255 }
            },
            margin: { top: 60 },
            addPageContent: function (data) {
                doc.text("@ViewData["Title"]", 40, 30);
            }
        });
        doc.save("książki.pdf");
    }, false);
</script>


@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

EBookLibrary/Views/LibraryManage/Loans.cshtml
@model EBookLibraryData.Models.ViewModels.LibraryManage.LoansManageViewModel

@{
    Layout = "_ManageLibraryLayout";
}

<h3>
    @ViewData["Title"]
</h3>
@if (Model.RemovedSuccessfully)
{
    <div class="alert alert-success" role="alert">
        @Model.RemoveSuccess
    </div>
}
else if (Model.RemoveError)
{
    <div class="alert alert-danger" role="alert">
        @Model.RemoveFailed
    </div>
}

@if (Model.Loans != null)
{
    <table id="table" class="table table-striped table-bordered" style="width: 100%">
        <thead>
            <tr>
                @foreach (var column in Model.ColumnNames)
                {
                    <th>@column</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var loan in Model.Loans)
            {
                <tr>
                    <td>@loan.LoanId</td>
                    <td>@loan.UserId</td>
                    <td>@loan.CopyId</td>
                    <td>
                        <div class="float-left pl-1 pb-3">
                            <!-- Button trigger modal -->
                            <button class="btn btn-danger" data-toggle="modal" data-target="#remove-modal-@loan.LoanId"><span class="fa fa-times"></span></button>

                            <!-- Modal -->
                            <div class="modal fade" id="remove-modal-@loan.LoanId" tabindex="-1" role="dialog" aria-labelledby="remove-modal-@loan.LoanId-label" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="remove-modal-@loan.LoanId-label">Usuwanie wypożyczenia</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form asp-controller="LibraryManage" asp-action="Loans" method="post" id="remove-author-form-@loan.LoanId"></form>
                                            Czy na pewno chcesz usunąć te wypożyczenie?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                                            <button class="btn btn-danger" name="LoanId" value="@loan.LoanId" form="remove-author-form-@loan.LoanId">Usuń</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info" role="alert">
        Brak elementów do wyświetlenia.
    </div>
}

EBookLibrary/Views/LibraryManage/Stats.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}